<?xml version="1.0"?>
<robot name="Swekbot 1.33.7" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.14159"/>
  <xacro:property name="base_width" value="0.069" />
  <xacro:property name="base_height" value="0.069" />
  <xacro:property name="servo_width" value="0.020" />
  <xacro:property name="servo_length" value="0.040" />
  <xacro:property name="shoulder_height" value="0.010" />
  <xacro:property name="shoulder_offset" value="0.015" />
  <xacro:property name="upperarm_length" value="0.121" />
  <xacro:property name="lowerarm_length" value="0.127" />
  <xacro:property name="gripper_length" value="0.086" />
  <xacro:property name="gripper_size" value="0.015" />
  <xacro:property name="gripper_open" value="0.10" />
  

  <!-- Links -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_width}" length="${base_height}"/>
      </geometry>
    </visual>
  </link>

  <link name="shoulder_rotate_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_width}" length="${shoulder_height}"/>
      </geometry>
    </visual>
  </link>

  <link name="shoulder_updown_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${servo_width}" length="${servo_length}"/>
      </geometry>
    </visual>
  </link>

  <link name="upperarm_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${upperarm_length} ${servo_width} ${servo_width}"/>
      </geometry>
    </visual>
  </link>

  <link name="elbow_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${servo_width}" length="${servo_length}"/>
      </geometry>
    </visual>
  </link>

  <link name="lowerarm_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${lowerarm_length} ${servo_width} ${servo_width}"/>
      </geometry>
    </visual>
  </link>

  <link name="wrist_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${servo_width}" length="${servo_length}"/>
      </geometry>
    </visual>
  </link>

  <link name="gripper_base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_size} ${gripper_open+gripper_size*2} ${gripper_size}"/>
      </geometry>
    </visual>
  </link>

  <link name="gripper_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_length} ${gripper_size} ${gripper_size}"/>
      </geometry>
    </visual>
  </link>
  <link name="gripper_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_length} ${gripper_size} ${gripper_size}"/>
      </geometry>
    </visual>
  </link>

  <!-- Joints -->  
  <joint name="shoulder_rotate_joint" type="revolute">
    <origin xyz="0 0 ${base_height + shoulder_height}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="shoulder_rotate_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="3.67"/>
  </joint>

  <joint name="shoulder_updown_joint" type="revolute">
    <origin xyz="0 0 ${shoulder_offset}" rpy="${M_PI/2} 0 0"/>
    <parent link="shoulder_rotate_link"/>
    <child link="shoulder_updown_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="${M_PI}" effort="0" velocity="3.67"/>
  </joint>

  <joint name="upperarm_joint" type="fixed">
    <origin xyz="${upperarm_length/2} 0 0" rpy="${M_PI/2} 0 0"/>
    <parent link="shoulder_updown_link"/>
    <child link="upperarm_link"/>
  </joint>

  <joint name="elbow_joint" type="revolute">
    <origin xyz="${upperarm_length/2} 0 0" rpy="${M_PI/2} 0 0"/>
    <parent link="upperarm_link"/>
    <child link="elbow_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="3.67"/>
  </joint>

  <joint name="lowerarm_joint" type="fixed">
    <origin xyz="${lowerarm_length/2} 0 0" rpy="${M_PI/2} 0 0"/>
    <parent link="elbow_link"/>
    <child link="lowerarm_link"/>
  </joint>

  <joint name="wrist_joint" type="revolute">
    <origin xyz="${upperarm_length/2} 0 0" rpy="${M_PI/2} 0 0"/>
    <parent link="lowerarm_link"/>
    <child link="wrist_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="3.67"/>
  </joint>

  <joint name="gripper_base_joint" type="fixed">
    <origin xyz="${servo_width} 0 0" rpy="0 0 0"/>
    <parent link="wrist_link"/>
    <child link="gripper_base_link"/>
  </joint>

  <joint name="gripper_left_joint" type="prismatic">
    <origin xyz="${gripper_length/2} ${gripper_size/2} 0" rpy="${M_PI/2} 0 0"/>
    <parent link="gripper_base_link"/>
    <child link="gripper_left_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${gripper_open/2}" upper="0" effort="0" velocity="3.67"/>
  </joint>

  <joint name="gripper_right_joint" type="prismatic">
    <origin xyz="${gripper_length/2} -${gripper_size/2} 0" rpy="${M_PI/2} 0 0"/>
    <parent link="gripper_base_link"/>
    <child link="gripper_right_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="${gripper_open/2}" effort="0" velocity="3.67"/>
  </joint>

</robot>
